#include "catalog.h"

static const StubExport exports_Kernel[] = {
    { "__error" },
    { "__stack_chk_fail" },
    { "__tls_get_addr" },
    { "sceKernelAllocateDirectMemory" },
    { "sceKernelGetProsperoSystemSwVersion" },
    { "sceKernelGetAllowedSdkVersionOnSystem" },
    { "sysctlbyname" },
    { "sceKernelAvailableDirectMemorySize" },
    { "sceKernelAvailableFlexibleMemorySize" },
    { "sceKernelCheckReachability" },
    { "sceKernelClockGettime" },
    { "sceKernelClose" },
    { "sceKernelDlsym" },
    { "sceKernelGetCurrentCpu" },
    { "sceKernelGetDirectMemorySize" },
    { "sceKernelGetProcessTime" },
    { "sceKernelGetdents" },
    { "sceKernelGetdirentries" },
    { "sceKernelLoadStartModule" },
    { "sceKernelLseek" },
    { "sceKernelMapDirectMemory" },
    { "sceKernelConfiguredFlexibleMemorySize" },
    { "sceKernelReserveVirtualRange" },
    { "sceKernelQueryMemoryProtection" },
    { "sceKernelMapFlexibleMemory" },
    { "sceKernelMapNamedFlexibleMemory" },
    { "sceKernelMemoryPoolCommit" },
    { "sceKernelMemoryPoolDecommit" },
    { "sceKernelMemoryPoolExpand" },
    { "sceKernelMemoryPoolReserve" },
    { "sceKernelMkdir" },
    { "sceKernelMprotect" },
    { "sceKernelMunmap" },
    { "sceKernelOpen" },
    { "sceKernelRead" },
    { "sceKernelReleaseDirectMemory" },
    { "sceKernelReleaseFlexibleMemory" },
    { "sceKernelRename" },
    { "sceKernelRmdir" },
    { "sceKernelSendNotificationRequest" },
    { "sceKernelStopUnloadModule" },
    { "sceKernelTruncate" },
    { "sceKernelUnlink" },
    { "sceKernelUsleep" },
    { "sceKernelGetAppInfo" },
    { "sceKernelVirtualQuery" },
    { "sceKernelWrite" },
    { "scePthreadGetthreadid" },
    { "scePthreadCondattrInit" },
    { "scePthreadCondattrDestroy" },
    { "scePthreadMutexattrInit" },
    { "scePthreadMutexattrSettype" },
    { "scePthreadMutexattrDestroy" },
    { "scePthreadCondBroadcast" },
    { "scePthreadCondDestroy" },
    { "scePthreadCondInit" },
    { "scePthreadCondSignal" },
    { "scePthreadCondWait" },
    { "scePthreadCreate" },
    { "scePthreadDetach" },
    { "scePthreadExit" },
    { "scePthreadGetspecific" },
    { "scePthreadJoin" },
    { "scePthreadKeyCreate" },
    { "scePthreadKeyDelete" },
    { "scePthreadMutexDestroy" },
    { "scePthreadMutexInit" },
    { "scePthreadMutexLock" },
    { "scePthreadMutexTrylock" },
    { "scePthreadMutexUnlock" },
    { "scePthreadRename" },
    { "scePthreadCondattrSetclock" },
    { "scePthreadGetaffinity" },
    { "scePthreadSetaffinity" },
    { "scePthreadSelf" },
    { "scePthreadSetspecific" },
    { "scePthreadYield" },
    { "sceKernelGetProcessTimeCounter" },
    { "sceKernelGetProcessTimeCounterFrequency" },
    { "sceKernelReadTsc" },
    { "sceKernelGetTscFrequency" },
    { "sceKernelNanosleep" },
    { "sceKernelClockGetres" },
    { "scePthreadSetprio" },
    { "scePthreadGetprio" },
    { "sceKernelCreateEqueue" },
    { "sceKernelDeleteEqueue" },
    { "sceKernelWaitEqueue" },
    { "sceKernelAddTimerEvent" },
    { "sceKernelDeleteTimerEvent" },
    { "sceKernelAddHRTimerEvent" },
    { "sceKernelDeleteHRTimerEvent" },
    { "sceKernelAddReadEvent" },
    { "sceKernelDeleteReadEvent" },
    { "sceKernelAddWriteEvent" },
    { "sceKernelDeleteWriteEvent" },
    { "sceKernelAddFileEvent" },
    { "sceKernelDeleteFileEvent" },
    { "sceKernelAddUserEvent" },
    { "sceKernelAddUserEventEdge" },
    { "sceKernelDeleteUserEvent" },
    { "sceKernelTriggerUserEvent" },
    { "sceKernelGetEventFilter" },
    { "sceKernelGetEventId" },
    { "sceKernelGetEventData" },
    { "sceKernelGetEventFflags" },
    { "sceKernelGetEventError" },
    { "sceKernelGetEventUserData" },
    { "sceKernelCreateEventFlag" },
    { "sceKernelDeleteEventFlag" },
    { "sceKernelWaitEventFlag" },
    { "sceKernelPollEventFlag" },
    { "sceKernelSetEventFlag" },
    { "sceKernelClearEventFlag" },
    { "sceKernelCancelEventFlag" },
    { "sceKernelCreateSema" },
    { "sceKernelDeleteSema" },
    { "sceKernelWaitSema" },
    { "sceKernelPollSema" },
    { "sceKernelSignalSema" },
    { "sceKernelCancelSema" },
    { "scePthreadGetschedparam" },
    { "scePthreadSetschedparam" },
    { "scePthreadGetcpuclockid" },
    { "scePthreadEqual" },
    { "scePthreadAttrInit" },
    { "scePthreadAttrDestroy" },
    { "scePthreadAttrGet" },
    { "scePthreadAttrSetstacksize" },
    { "scePthreadAttrGetstacksize" },
    { "scePthreadAttrGetstack" },
    { "scePthreadAttrSetguardsize" },
    { "scePthreadAttrGetguardsize" },
    { "scePthreadAttrSetdetachstate" },
    { "scePthreadAttrGetdetachstate" },
    { "scePthreadAttrSetaffinity" },
    { "scePthreadAttrGetaffinity" },
    { "scePthreadAttrSetschedparam" },
    { "scePthreadAttrGetschedparam" },
    { "scePthreadAttrSetschedpolicy" },
    { "scePthreadAttrGetschedpolicy" },
    { "scePthreadAttrSetinheritsched" },
    { "scePthreadAttrGetinheritsched" },
    { "sceKernelDirectMemoryQuery" },
    { "sceKernelGetDirectMemoryType" },
    { "sceKernelIsStack" },
    { "sceKernelSetVirtualRangeName" },
    { "sceKernelGetPageTableStats" },
    { "sceKernelMsync" },
    { "sceKernelMtypeprotect" },
    { "sceKernelAllocateMainDirectMemory" },
    { "sceKernelMapNamedDirectMemory" },
    { "sceKernelCheckedReleaseDirectMemory" },
    { "sceKernelMemoryPoolGetBlockStats" },
    { "getargc" },
    { "getargv" },
    { "sceKernelUuidCreate" },
    { "kqueue" },
    { "kevent" },
};

static const StubExport exports_Posix[] = {
    { "chmod" },
    { "clock_gettime" },
    { "close" },
    { "fchmod" },
    { "socket" },
    { "bind" },
    { "listen" },
    { "accept" },
    { "connect" },
    { "send" },
    { "recv" },
    { "setsockopt" },
    { "shutdown" },
    { "fcntl" },
    { "flock" },
    { "fstat" },
    { "fsync" },
    { "ftruncate" },
    { "getdents" },
    { "getpid" },
    { "getsockopt" },
    { "gettimeofday" },
    { "lseek" },
    { "madvise" },
    { "mkdir" },
    { "mlock" },
    { "mprotect" },
    { "msync" },
    { "munlock" },
    { "munmap" },
    { "nanosleep" },
    { "open" },
    { "pread" },
    { "preadv" },
    { "pthread_attr_destroy" },
    { "pthread_attr_get_np" },
    { "pthread_attr_getstack" },
    { "pthread_attr_init" },
    { "pthread_attr_setdetachstate" },
    { "pthread_attr_setstacksize" },
    { "pthread_cond_broadcast" },
    { "pthread_cond_destroy" },
    { "pthread_cond_init" },
    { "pthread_cond_signal" },
    { "pthread_cond_timedwait" },
    { "pthread_cond_wait" },
    { "pthread_condattr_destroy" },
    { "utimes" },
    { "futimes" },
    { "pthread_condattr_init" },
    { "pthread_condattr_setclock" },
    { "pthread_create" },
    { "pthread_getspecific" },
    { "pthread_key_create" },
    { "pthread_mutex_destroy" },
    { "pthread_mutex_init" },
    { "pthread_mutex_lock" },
    { "pthread_mutex_unlock" },
    { "pthread_mutexattr_destroy" },
    { "pthread_mutexattr_init" },
    { "pthread_mutexattr_settype" },
    { "pthread_rwlock_rdlock" },
    { "pthread_rwlock_unlock" },
    { "pthread_rwlock_wrlock" },
    { "pthread_self" },
    { "pthread_setcancelstate" },
    { "pthread_setspecific" },
    { "pthread_sigmask" },
    { "pwrite" },
    { "pwritev" },
    { "read" },
    { "rename" },
    { "rmdir" },
    { "sched_yield" },
    { "stat" },
    { "sync" },
    { "unlink" },
    { "write" },
    { "getpagesize" },
    { "getdtablesize" },
    { "sched_get_priority_max" },
    { "sched_get_priority_min" },
    { "mlockall" },
    { "munlockall" },
    { "pthread_rename_np" },
    { "sysctl" },
    { "getmntinfo" },
    { "ptrace" },
    { "wait4" },
    { "waitpid" },
    { "getuid" },
    { "geteuid" },
};

static const StubExport exports_OpenPsId[] = {
    { "sceKernelGetOpenPsId" },
};

static const StubExport exports_C[] = {
    { "Need_sceLibc" },
    { "_Unwind_Resume" },
    { "__cxa_allocate_exception" },
    { "__cxa_atexit" },
    { "__cxa_begin_catch" },
    { "__cxa_end_catch" },
    { "__cxa_finalize" },
    { "__cxa_free_exception" },
    { "__cxa_guard_acquire" },
    { "__cxa_guard_release" },
    { "__cxa_rethrow" },
    { "__cxa_throw" },
    { "__isthreaded" },
    { "__stderrp" },
    { "__stdinp" },
    { "__stdoutp" },
    { "_init_env" },
    { "abort" },
    { "acos" },
    { "acosf" },
    { "acosh" },
    { "acoshf" },
    { "aligned_alloc" },
    { "asin" },
    { "asinf" },
    { "asinh" },
    { "asinhf" },
    { "asprintf" },
    { "atan" },
    { "atan2" },
    { "atan2f" },
    { "atanf" },
    { "atanh" },
    { "atanhf" },
    { "atexit" },
    { "bcmp" },
    { "bsearch" },
    { "calloc" },
    { "catchReturnFromMain" },
    { "cbrt" },
    { "cbrtf" },
    { "ceil" },
    { "ceilf" },
    { "copysign" },
    { "copysignf" },
    { "cos" },
    { "cosf" },
    { "cosh" },
    { "coshf" },
    { "exit" },
    { "exp" },
    { "exp2" },
    { "exp2f" },
    { "expf" },
    { "expm1" },
    { "expm1f" },
    { "fabs" },
    { "fabsf" },
    { "fclose" },
    { "fdim" },
    { "fdimf" },
    { "feof" },
    { "fflush" },
    { "fgets" },
    { "fileno" },
    { "floor" },
    { "floorf" },
    { "fma" },
    { "fmaf" },
    { "fmax" },
    { "fmaxf" },
    { "fmin" },
    { "fminf" },
    { "fmod" },
    { "fmodf" },
    { "fopen" },
    { "fprintf" },
    { "fputs" },
    { "fread" },
    { "free" },
    { "fwrite" },
    { "hypot" },
    { "hypotf" },
    { "ilogb" },
    { "ilogbf" },
    { "isspace" },
    { "log" },
    { "log10" },
    { "log10f" },
    { "log1p" },
    { "log1pf" },
    { "log2" },
    { "log2f" },
    { "logb" },
    { "logbf" },
    { "logf" },
    { "longjmp" },
    { "lrand48" },
    { "malloc" },
    { "malloc_usable_size" },
    { "memchr" },
    { "memcmp" },
    { "memcpy" },
    { "memmove" },
    { "memset" },
    { "modf" },
    { "modff" },
    { "nearbyint" },
    { "nearbyintf" },
    { "nextafter" },
    { "nextafterf" },
    { "posix_memalign" },
    { "pow" },
    { "powf" },
    { "printf" },
    { "puts" },
    { "qsort" },
    { "realloc" },
    { "remainder" },
    { "remainderf" },
    { "remquo" },
    { "remquof" },
    { "rint" },
    { "rintf" },
    { "round" },
    { "roundf" },
    { "scalbn" },
    { "scalbnf" },
    { "setjmp" },
    { "sin" },
    { "sinf" },
    { "sinh" },
    { "sinhf" },
    { "snprintf" },
    { "sqrt" },
    { "sqrtf" },
    { "srand48" },
    { "sscanf" },
    { "strcasecmp" },
    { "strcat" },
    { "strchr" },
    { "strcmp" },
    { "strcpy" },
    { "strdup" },
    { "strerror" },
    { "strerror_r" },
    { "strlen" },
    { "strncat" },
    { "strncmp" },
    { "strncpy" },
    { "strrchr" },
    { "strstr" },
    { "strtok_r" },
    { "strtol" },
    { "strtoll" },
    { "strtoul" },
    { "strtoull" },
    { "tan" },
    { "tanf" },
    { "tanh" },
    { "tanhf" },
    { "time" },
    { "trunc" },
    { "truncf" },
    { "vfprintf" },
    { "vsnprintf" },
};

static const StubExport exports_VideoOut[] = {
    { "sceVideoOutOpen" },
    { "sceVideoOutClose" },
    { "sceVideoOutSetBufferAttribute2" },
    { "sceVideoOutRegisterBuffers2" },
    { "sceVideoOutUnregisterBuffers" },
    { "sceVideoOutSetFlipRate" },
    { "sceVideoOutSubmitFlip" },
    { "sceVideoOutIsFlipPending" },
    { "sceVideoOutGetFlipStatus" },
    { "sceVideoOutWaitVblank" },
};

static const StubExport exports_Pad[] = {
    { "scePadInit" },
    { "scePadOpen" },
    { "scePadClose" },
    { "scePadReadState" },
    { "scePadSetVibration" },
    { "scePadSetLightBar" },
    { "scePadResetLightBar" },
    { "scePadGetControllerInformation" },
    { "scePadGetHandle" },
    { "scePadGetTriggerEffectState" },
    { "scePadRead" },
    { "scePadResetOrientation" },
    { "scePadSetAngularVelocityDeadbandState" },
    { "scePadSetMotionSensorState" },
    { "scePadSetTiltCorrectionState" },
    { "scePadSetTriggerEffect" },
    { "scePadSetVibrationMode" },
    { "scePadSetVibrationTriggerEffectWeakWhileEmbeddedMicInUse" },
};

static const StubExport exports_UserService[] = {
    { "sceUserServiceInitialize" },
    { "sceUserServiceTerminate" },
    { "sceUserServiceGetInitialUser" },
    { "sceUserServiceGetLoginUserIdList" },
    { "sceUserServiceGetUserName" },
    { "sceUserServiceGetUserNumber" },
    { "sceUserServiceGetAccessibilityChatTranscription" },
    { "sceUserServiceGetAccessibilityPressAndHoldDelay" },
    { "sceUserServiceGetAccessibilityTriggerEffect" },
    { "sceUserServiceGetAccessibilityVibration" },
    { "sceUserServiceGetAgeLevel" },
    { "sceUserServiceGetEvent" },
    { "sceUserServiceGetGamePresets" },
    { "sceUserServiceInitialize2" },
};

static const StubExport exports_SystemService[] = {
    { "sceSystemServiceHideSplashScreen" },
    { "sceSystemServiceParamGetInt" },
    { "sceSystemServiceParamGetString" },
    { "sceSystemServiceLaunchApp" },
    { "sceSystemServiceLoadExec" },
    { "sceSystemServicePowerTick" },
    { "sceSystemServiceReceiveEvent" },
    { "sceSystemServiceGetStatus" },
    { "sceSystemServiceGetDisplaySafeAreaInfo" },
    { "sceSystemServiceDisableMediaPlay" },
    { "sceSystemServiceReenableMediaPlay" },
    { "sceSystemServiceSetGpuLoadEmulationMode" },
    { "sceSystemServiceGetGpuLoadEmulationMode" },
    { "sceSystemServiceReportAbnormalTermination" },
    { "sceSystemServiceLaunchWebBrowser" },
};

static const StubExport exports_AudioOut[] = {
    { "sceAudioOutInit" },
    { "sceAudioOutOpen" },
    { "sceAudioOutClose" },
    { "sceAudioOutOutput" },
    { "sceAudioOutOutputs" },
    { "sceAudioOutSetVolume" },
    { "sceAudioOutGetPortState" },
    { "sceAudioOutGetLastOutputTime" },
};

static const StubExport exports_AudioOut2[] = {
    { "sceAudioOut2Initialize" },
    { "sceAudioOut2ContextResetParam" },
    { "sceAudioOut2ContextQueryMemory" },
    { "sceAudioOut2ContextCreate" },
    { "sceAudioOut2ContextDestroy" },
    { "sceAudioOut2ContextSetAttributes" },
    { "sceAudioOut2ContextAdvance" },
    { "sceAudioOut2ContextPush" },
    { "sceAudioOut2ContextGetQueueLevel" },
    { "sceAudioOut2PortCreate" },
    { "sceAudioOut2PortDestroy" },
    { "sceAudioOut2PortSetAttributes" },
    { "sceAudioOut2PortGetState" },
    { "sceAudioOut2GetSpeakerArrayMemorySize" },
    { "sceAudioOut2SpeakerArrayCreate" },
    { "sceAudioOut2SpeakerArrayDestroy" },
    { "sceAudioOut2GetSpeakerArrayCoefficients" },
    { "sceAudioOut2GetSpeakerArrayAmbisonicsCoefficients" },
    { "sceAudioOut2GetSystemState" },
    { "sceAudioOut2GetSpeakerInfo" },
    { "sceAudioOut2UserCreate" },
    { "sceAudioOut2UserDestroy" },
    { "sceAudioOut2UserGetSupportedAttributes" },
    { "sceAudioOut2EnableChat" },
    { "sceAudioOut2DisableChat" },
    { "sceAudioOut2MasteringInit" },
    { "sceAudioOut2MasteringTerm" },
    { "sceAudioOut2MasteringSetParam" },
    { "sceAudioOut2MasteringGetState" },
};

static const StubExport exports_Sysmodule[] = {
    { "sceSysmoduleLoadModule" },
    { "sceSysmoduleUnloadModule" },
    { "sceSysmoduleIsLoaded" },
};

static const StubExport exports_PngDec[] = {
    { "scePngDecCreate" },
    { "scePngDecDelete" },
    { "scePngDecParseHeader" },
    { "scePngDecQueryMemorySize" },
    { "scePngDecDecode" },
};

static const StubExport exports_PngEnc[] = {
    { "scePngEncQueryMemorySize" },
    { "scePngEncCreate" },
    { "scePngEncEncode" },
    { "scePngEncDelete" },
};

static const StubExport exports_JpegDec[] = {
    { "sceJpegDecCreate" },
    { "sceJpegDecDelete" },
    { "sceJpegDecParseHeader" },
    { "sceJpegDecQueryMemorySize" },
    { "sceJpegDecDecode" },
};

static const StubExport exports_JpegEnc[] = {
    { "sceJpegEncQueryMemorySize" },
    { "sceJpegEncCreate" },
    { "sceJpegEncEncode" },
    { "sceJpegEncDelete" },
};

static const StubExport exports_AudioIn[] = {
    { "sceAudioInOpen" },
    { "sceAudioInInput" },
    { "sceAudioInGetSilentState" },
    { "sceAudioInClose" },
};

static const StubExport exports_Audiodec[] = {
    { "sceAudiodecInitLibrary" },
    { "sceAudiodecTermLibrary" },
    { "sceAudiodecCreateDecoder" },
    { "sceAudiodecDeleteDecoder" },
    { "sceAudiodecDecode" },
    { "sceAudiodecClearContext" },
};

static const StubExport exports_M4aacEnc[] = {
    { "sceM4aacEncCreateEncoder" },
    { "sceM4aacEncDeleteEncoder" },
    { "sceM4aacEncEncode" },
    { "sceM4aacEncFlush" },
    { "sceM4aacEncClearContext" },
};

static const StubExport exports_At9Enc[] = {
    { "sceAt9EncQueryMemSize" },
    { "sceAt9EncCreateEncoder" },
    { "sceAt9EncEncode" },
    { "sceAt9EncFlush" },
    { "sceAt9EncClearContext" },
};

static const StubExport exports_Ngs2[] = {
    { "sceNgs2SystemEnumHandles" },
    { "sceNgs2SystemResetOption" },
    { "sceNgs2SystemQueryBufferSize" },
    { "sceNgs2SystemCreate" },
    { "sceNgs2SystemCreateWithAllocator" },
    { "sceNgs2SystemDestroy" },
    { "sceNgs2SystemRunCommands" },
    { "sceNgs2SystemQueryInfo" },
    { "sceNgs2SystemLock" },
    { "sceNgs2SystemUnlock" },
    { "sceNgs2SystemSetUserData" },
    { "sceNgs2SystemGetUserData" },
    { "sceNgs2SystemGetInfo" },
    { "sceNgs2SystemSetGrainSamples" },
    { "sceNgs2SystemSetSampleRate" },
    { "sceNgs2SystemEnumRackHandles" },
    { "sceNgs2SystemRender" },
    { "sceNgs2RackQueryBufferSize" },
    { "sceNgs2RackCreate" },
    { "sceNgs2RackCreateWithAllocator" },
    { "sceNgs2RackDestroy" },
    { "sceNgs2RackRunCommands" },
    { "sceNgs2RackQueryInfo" },
    { "sceNgs2RackLock" },
    { "sceNgs2RackUnlock" },
    { "sceNgs2RackSetUserData" },
    { "sceNgs2RackGetUserData" },
    { "sceNgs2RackGetInfo" },
    { "sceNgs2RackGetVoiceHandle" },
    { "sceNgs2VoiceRunCommands" },
    { "sceNgs2VoiceQueryInfo" },
    { "sceNgs2VoiceControl" },
    { "sceNgs2VoiceGetStateFlags" },
    { "sceNgs2VoiceGetState" },
    { "sceNgs2VoiceGetOwner" },
    { "sceNgs2VoiceGetMatrixInfo" },
    { "sceNgs2VoiceGetPortInfo" },
    { "sceNgs2StreamResetOption" },
    { "sceNgs2StreamQueryBufferSize" },
    { "sceNgs2StreamCreate" },
    { "sceNgs2StreamCreateWithAllocator" },
    { "sceNgs2StreamDestroy" },
    { "sceNgs2StreamRunCommands" },
    { "sceNgs2StreamQueryInfo" },
    { "sceNgs2ParseWaveformData" },
    { "sceNgs2ParseWaveformFile" },
    { "sceNgs2ParseWaveformUser" },
    { "sceNgs2CalcWaveformBlock" },
    { "sceNgs2GetWaveformFrameInfo" },
    { "sceNgs2JobSchedulerResetOption" },
    { "sceNgs2GeomResetListenerParam" },
    { "sceNgs2GeomResetSourceParam" },
    { "sceNgs2GeomCalcListener" },
    { "sceNgs2GeomApply" },
    { "sceNgs2PanInit" },
    { "sceNgs2PanGetVolumeMatrix" },
    { "sceNgs2ReportRegisterHandler" },
    { "sceNgs2ReportUnregisterHandler" },
    { "sceNgs2CustomRackGetModuleInfo" },
};

static const StubExport exports_Audio3d[] = {
    { "sceAudio3dInitialize" },
    { "sceAudio3dTerminate" },
    { "sceAudio3dPortOpen" },
    { "sceAudio3dPortClose" },
    { "sceAudio3dPortSetAttribute" },
    { "sceAudio3dPortAdvance" },
    { "sceAudio3dPortPush" },
    { "sceAudio3dPortGetAttributesSupported" },
    { "sceAudio3dPortGetQueueLevel" },
    { "sceAudio3dObjectReserve" },
    { "sceAudio3dObjectUnreserve" },
    { "sceAudio3dObjectSetAttributes" },
    { "sceAudio3dBedWrite" },
    { "sceAudio3dBedWrite2" },
    { "sceAudio3dGetSpeakerArrayMemorySize" },
    { "sceAudio3dCreateSpeakerArray" },
    { "sceAudio3dDeleteSpeakerArray" },
    { "sceAudio3dGetSpeakerArrayMixCoefficients" },
    { "sceAudio3dGetSpeakerArrayMixCoefficients2" },
    { "sceAudio3dAudioOutOpen" },
    { "sceAudio3dAudioOutClose" },
    { "sceAudio3dAudioOutOutput" },
    { "sceAudio3dAudioOutOutputs" },
    { "sceAudio3dPortCreate" },
    { "sceAudio3dPortDestroy" },
    { "sceAudio3dPortFlush" },
};

static const StubExport exports_Ajm[] = {
    { "sceAjmInitialize" },
    { "sceAjmFinalize" },
    { "sceAjmMemoryRegister" },
    { "sceAjmMemoryUnregister" },
    { "sceAjmModuleRegister" },
    { "sceAjmModuleUnregister" },
    { "sceAjmInstanceCreate" },
    { "sceAjmInstanceExtend" },
    { "sceAjmInstanceSwitch" },
    { "sceAjmInstanceDestroy" },
    { "sceAjmBatchInitialize" },
    { "sceAjmBatchJobInitialize" },
    { "sceAjmBatchJobClearContext" },
    { "sceAjmBatchJobDecode" },
    { "sceAjmBatchJobDecodeSingle" },
    { "sceAjmBatchJobDecodeSplit" },
    { "sceAjmBatchJobEncode" },
    { "sceAjmBatchJobGetInfo" },
    { "sceAjmBatchJobGetCodecInfo" },
    { "sceAjmBatchJobSetGaplessDecode" },
    { "sceAjmBatchJobGetGaplessDecode" },
    { "sceAjmBatchJobSetResampleParameters" },
    { "sceAjmBatchJobSetResampleParametersEx" },
    { "sceAjmBatchJobGetResampleInfo" },
    { "sceAjmBatchStart" },
    { "sceAjmBatchWait" },
    { "sceAjmBatchCancel" },
    { "sceAjmBatchErrorDump" },
    { "sceAjmBatchJobGetStatistics" },
    { "sceAjmBatchJobControl" },
    { "sceAjmBatchJobRun" },
    { "sceAjmBatchJobRunSplit" },
};

static const StubExport exports_VideoRecording[] = {
    { "sceVideoRecordingGetStatus" },
    { "sceVideoRecordingQueryMemSize" },
    { "sceVideoRecordingOpen" },
    { "sceVideoRecordingStart" },
    { "sceVideoRecordingStop" },
    { "sceVideoRecordingClose" },
};

static const StubExport exports_Ces[] = {
    { "sceCesEucJpToUtf8" },
    { "sceCesEucKrToUtf8" },
    { "sceCesBig5ToUtf8" },
    { "sceCesUhcToUtf8" },
    { "sceCesUcsProfileInitEucJpX0208" },
    { "sceCesUcsProfileInitEucJpX0208Ss2" },
    { "sceCesUcsProfileInitEucJpX0208Ss2Ss3" },
    { "sceCesUcsProfileInitEucJpCp51932" },
    { "sceCesUcsProfileInitEucKr" },
    { "sceCesUcsProfileInitBig5Cp950" },
    { "sceCesUcsProfileInitUhc" },
};

static const StubExport exports_Depth2[] = {
    { "sceDepth2QueryMemory" },
    { "sceDepth2Initialize" },
    { "sceDepth2Terminate" },
    { "sceDepth2SetCommand" },
    { "sceDepth2Submit" },
    { "sceDepth2WaitAndExecutePostProcess" },
    { "sceDepth2SetRoi" },
    { "sceDepth2GetImage" },
};

static const StubExport exports_DeviceService[] = {
    { "sceDeviceServiceInitialize" },
    { "sceDeviceServiceTerminate" },
    { "sceDeviceServiceGetGeneration" },
    { "sceDeviceServiceGetEventState" },
    { "sceDeviceServiceQueryDeviceInfo_" },
};

static const StubExport exports_Videodec2[] = {
    { "sceVideodec2QueryComputeMemoryInfo" },
    { "sceVideodec2AllocateComputeQueue" },
    { "sceVideodec2ReleaseComputeQueue" },
    { "sceVideodec2QueryDecoderMemoryInfo" },
    { "sceVideodec2CreateDecoder" },
    { "sceVideodec2DeleteDecoder" },
    { "sceVideodec2Decode" },
    { "sceVideodec2Flush" },
    { "sceVideodec2Reset" },
};

static const StubExport exports_Rtc[] = {
    { "sceRtcGetCurrentClock" },
    { "sceRtcGetCurrentClockLocalTime" },
    { "sceRtcGetCurrentTick" },
    { "sceRtcGetCurrentNetworkTick" },
    { "sceRtcGetTickResolution" },
    { "sceRtcConvertUtcToLocalTime" },
    { "sceRtcConvertLocalTimeToUtc" },
    { "sceRtcSetTick" },
    { "sceRtcGetTick" },
};

static const StubExport exports_Random[] = {
    { "sceRandomGetRandomNumber" },
};

static const StubExport exports_Zlib[] = {
    { "sceZlibInitialize" },
    { "sceZlibFinalize" },
    { "sceZlibInflate" },
    { "sceZlibWaitForDone" },
    { "sceZlibGetResult" },
};

static const StubExport exports_Net[] = {
    { "sceNetPoolCreate" },
    { "sceNetPoolDestroy" },
    { "sceNetSocket" },
    { "sceNetBind" },
    { "sceNetListen" },
    { "sceNetAccept" },
    { "sceNetConnect" },
    { "sceNetSend" },
    { "sceNetSendto" },
    { "sceNetRecv" },
    { "sceNetRecvfrom" },
    { "sceNetSocketClose" },
    { "sceNetShutdown" },
    { "sceNetSocketAbort" },
    { "sceNetSetsockopt" },
    { "sceNetGetsockopt" },
    { "sceNetGetsockname" },
    { "sceNetGetpeername" },
    { "sceNetErrnoLoc" },
    { "sceNetEpollCreate" },
    { "sceNetEpollControl" },
    { "sceNetEpollWait" },
    { "sceNetEpollDestroy" },
    { "sceNetEpollAbort" },
    { "sceNetResolverCreate" },
    { "sceNetResolverStartNtoa" },
    { "sceNetResolverDestroy" },
    { "sceNetInit" },
};

static const StubExport exports_Ssl[] = {
    { "sceSslInit" },
    { "sceSslTerm" },
    { "sceSslClose" },
    { "sceSslConnect" },
    { "sceSslCreateConnection" },
    { "sceSslDeleteConnection" },
    { "sceSslDisableVerifyOption" },
    { "sceSslEnableVerifyOption" },
    { "sceSslGetAlpnSelected" },
    { "sceSslLoadCert" },
    { "sceSslRead" },
    { "sceSslRecv" },
    { "sceSslReuseConnection" },
    { "sceSslSend" },
    { "sceSslSetAlpn" },
    { "sceSslSetMinSslVersion" },
    { "sceSslSetVerifyCallback" },
    { "sceSslUnloadCert" },
    { "sceSslWrite" },
};

static const StubExport exports_Http[] = {
    { "sceHttpInit" },
    { "sceHttpTerm" },
    { "sceHttpCreateTemplate" },
    { "sceHttpDeleteTemplate" },
    { "sceHttpCreateConnectionWithURL" },
    { "sceHttpDeleteConnection" },
    { "sceHttpCreateRequestWithURL" },
    { "sceHttpDeleteRequest" },
    { "sceHttpSendRequest" },
    { "sceHttpGetStatusCode" },
    { "sceHttpGetResponseContentLength" },
    { "sceHttpReadData" },
    { "sceHttpSetConnectTimeOut" },
    { "sceHttpSetRecvTimeOut" },
    { "sceHttpAbortRequest" },
    { "sceHttpAddRequestHeader" },
    { "sceHttpCreateRequestWithURL2" },
    { "sceHttpGetAllResponseHeaders" },
    { "sceHttpGetAutoRedirect" },
    { "sceHttpGetLastErrno" },
    { "sceHttpParseResponseHeader" },
    { "sceHttpParseStatusLine" },
    { "sceHttpRemoveRequestHeader" },
    { "sceHttpSetAutoRedirect" },
    { "sceHttpSetChunkedTransferEnabled" },
    { "sceHttpSetInflateGZIPEnabled" },
    { "sceHttpSetRequestContentLength" },
    { "sceHttpSetResolveRetry" },
    { "sceHttpSetResolveTimeOut" },
    { "sceHttpSetResponseHeaderMaxSize" },
    { "sceHttpSetSendTimeOut" },
    { "sceHttpUriBuild" },
    { "sceHttpUriEscape" },
    { "sceHttpUriMerge" },
    { "sceHttpUriParse" },
    { "sceHttpUriSweepPath" },
    { "sceHttpUriUnescape" },
    { "sceHttpsDisableOption" },
    { "sceHttpsEnableOption" },
    { "sceHttpsGetSslError" },
    { "sceHttpsLoadCert" },
    { "sceHttpsSetSslVersion" },
    { "sceHttpsUnloadCert" },
};

static const StubExport exports_Http2[] = {
    { "sceHttp2Init" },
    { "sceHttp2Term" },
    { "sceHttp2CreateTemplate" },
    { "sceHttp2DeleteTemplate" },
    { "sceHttp2CreateRequestWithURL" },
    { "sceHttp2DeleteRequest" },
    { "sceHttp2SendRequest" },
    { "sceHttp2GetStatusCode" },
    { "sceHttp2ReadData" },
};

static const StubExport exports_KernelSys[] = {
    { "sceKernelGetHwModelName" },
    { "sceKernelGetHwSerialNumber" },
    { "sceKernelGetCpuFrequency" },
    { "sceKernelGetCpuTemperature" },
    { "sceKernelGetSocSensorTemperature" },
};

static const StubExport exports_ContentDelete[] = {
    { "sceContentDeleteInitialize" },
    { "sceContentDeleteTerminate" },
    { "sceContentDeleteById" },
    { "sceContentDeleteByPath" },
};

static const StubExport exports_ContentExport[] = {
    { "sceContentExportInit2" },
    { "sceContentExportTerm" },
    { "sceContentExportStart" },
    { "sceContentExportFinish" },
    { "sceContentExportFromFile" },
    { "sceContentExportCancel" },
    { "sceContentExportGetProgress" },
    { "sceContentExportFromData" },
    { "sceContentExportFromDataWithThumbnail" },
    { "sceContentExportFromFileWithThumbnail" },
};

static const StubExport exports_ContentSearch[] = {
    { "sceContentSearchInit" },
    { "sceContentSearchTerm" },
    { "sceContentSearchGetContentLastUpdateId" },
    { "sceContentSearchGetNumOfContent" },
    { "sceContentSearchGetTotalContentSize" },
    { "sceContentSearchSearchContent" },
    { "sceContentSearchOpenMetadata" },
    { "sceContentSearchOpenMetadataByContentId" },
    { "sceContentSearchCloseMetadata" },
    { "sceContentSearchGetMetadataFieldInfo" },
    { "sceContentSearchGetMetadataValue" },
};

static const StubExport exports_PlayGo[] = {
    { "scePlayGoInitialize" },
    { "scePlayGoTerminate" },
    { "scePlayGoOpen" },
    { "scePlayGoClose" },
    { "scePlayGoGetLocus" },
    { "scePlayGoGetProgress" },
};

static const StubExport exports_AppContent[] = {
    { "sceAppContentInitialize" },
    { "sceAppContentAppParamGetInt" },
    { "sceAppContentAddcontEnqueueDownload" },
    { "sceAppContentAddcontMount" },
    { "sceAppContentAddcontUnmount" },
    { "sceAppContentDownloadDataFormat" },
    { "sceAppContentDownloadDataGetAvailableSpaceKb" },
    { "sceAppContentGetAddcontDownloadProgress" },
    { "sceAppContentTemporaryDataFormat" },
    { "sceAppContentTemporaryDataGetAvailableSpaceKb" },
    { "sceAppContentTemporaryDataMount2" },
    { "sceAppContentTemporaryDataUnmount" },
};

static const StubExport exports_NetCtl[] = {
    { "sceNetCtlInit" },
    { "sceNetCtlTerm" },
    { "sceNetCtlGetState" },
    { "sceNetCtlGetInfo" },
};

static const StubExport exports_SaveData[] = {
    { "sceSaveDataInitialize3" },
    { "sceSaveDataTerminate" },
    { "sceSaveDataMount3" },
    { "sceSaveDataUmount2" },
    { "sceSaveDataGetMountInfo" },
    { "sceSaveDataDelete" },
    { "sceSaveDataDirNameSearch" },
    { "sceSaveDataBackup" },
    { "sceSaveDataCommit" },
    { "sceSaveDataCreateTransactionResource" },
    { "sceSaveDataDeleteTransactionResource" },
    { "sceSaveDataGetParam" },
    { "sceSaveDataLoadIcon" },
    { "sceSaveDataPrepare" },
    { "sceSaveDataSaveIcon" },
    { "sceSaveDataSaveIconByPath" },
    { "sceSaveDataSetParam" },
};

static const StubExport exports_Keyboard[] = {
    { "sceKeyboardInit" },
    { "sceKeyboardOpen" },
    { "sceKeyboardClose" },
    { "sceKeyboardReadState" },
    { "sceKeyboardRead" },
    { "sceKeyboardGetKey2Char" },
};

static const StubExport exports_Mouse[] = {
    { "sceMouseInit" },
    { "sceMouseOpen" },
    { "sceMouseClose" },
    { "sceMouseRead" },
};

static const StubExport exports_CommonDialog[] = {
    { "sceCommonDialogInitialize" },
    { "sceCommonDialogIsUsed" },
};

static const StubExport exports_ImeDialog[] = {
    { "sceImeDialogInit" },
    { "sceImeDialogGetStatus" },
    { "sceImeDialogGetResult" },
    { "sceImeDialogAbort" },
    { "sceImeDialogTerm" },
    { "sceImeDialogGetPanelSizeExtended" },
    { "sceImeDialogGetPanelPositionAndForm" },
};

static const StubExport exports_ErrorDialog[] = {
    { "sceErrorDialogInitialize" },
    { "sceErrorDialogTerminate" },
    { "sceErrorDialogOpen" },
    { "sceErrorDialogClose" },
    { "sceErrorDialogUpdateStatus" },
    { "sceErrorDialogGetStatus" },
};

static const StubExport exports_MsgDialog[] = {
    { "sceMsgDialogInitialize" },
    { "sceMsgDialogTerminate" },
    { "sceMsgDialogOpen" },
    { "sceMsgDialogClose" },
    { "sceMsgDialogUpdateStatus" },
    { "sceMsgDialogGetStatus" },
    { "sceMsgDialogGetResult" },
    { "sceMsgDialogProgressBarInc" },
    { "sceMsgDialogProgressBarSetValue" },
    { "sceMsgDialogProgressBarSetMsg" },
};

static const StubExport exports_SaveDataDialog[] = {
    { "sceSaveDataDialogInitialize" },
    { "sceSaveDataDialogTerminate" },
    { "sceSaveDataDialogUpdateStatus" },
    { "sceSaveDataDialogGetStatus" },
    { "sceSaveDataDialogOpen" },
    { "sceSaveDataDialogGetResult" },
    { "sceSaveDataDialogClose" },
    { "sceSaveDataDialogIsReadyToDisplay" },
};

static const StubExport exports_WebBrowserDialog[] = {
    { "sceWebBrowserDialogInitialize" },
    { "sceWebBrowserDialogOpen" },
    { "sceWebBrowserDialogUpdateStatus" },
    { "sceWebBrowserDialogGetStatus" },
    { "sceWebBrowserDialogGetResult" },
    { "sceWebBrowserDialogClose" },
    { "sceWebBrowserDialogTerminate" },
    { "sceWebBrowserDialogResetCookie" },
};

static const StubExport exports_AvPlayer[] = {
    { "sceAvPlayerInit" },
    { "sceAvPlayerInitEx" },
    { "sceAvPlayerPostInit" },
    { "sceAvPlayerAddSource" },
    { "sceAvPlayerStart" },
    { "sceAvPlayerStop" },
    { "sceAvPlayerPause" },
    { "sceAvPlayerResume" },
    { "sceAvPlayerIsActive" },
    { "sceAvPlayerSetLooping" },
    { "sceAvPlayerGetAudioData" },
    { "sceAvPlayerGetVideoDataEx" },
    { "sceAvPlayerCurrentTime" },
    { "sceAvPlayerJumpToTime" },
    { "sceAvPlayerStreamCount" },
    { "sceAvPlayerGetStreamInfo" },
    { "sceAvPlayerEnableStream" },
    { "sceAvPlayerDisableStream" },
    { "sceAvPlayerChangeStream" },
    { "sceAvPlayerSetLogCallback" },
    { "sceAvPlayerClose" },
};

static const StubExport exports_Font[] = {
    { "sceFontMemoryInit" },
    { "sceFontMemoryTerm" },
    { "sceFontCreateLibraryWithEdition" },
    { "sceFontDestroyLibrary" },
    { "sceFontSupportExternalFonts" },
    { "sceFontOpenFontMemory" },
    { "sceFontCloseFont" },
    { "sceFontCreateRendererWithEdition" },
    { "sceFontDestroyRenderer" },
    { "sceFontBindRenderer" },
    { "sceFontUnbindRenderer" },
    { "sceFontSetupRenderScalePixel" },
    { "sceFontGetRenderCharGlyphMetrics" },
    { "sceFontGetHorizontalLayout" },
    { "sceFontRenderCharGlyphImageHorizontal" },
    { "sceFontRenderSurfaceInit" },
    { "sceFontRenderSurfaceSetScissor" },
    { "sceFontGetRenderScaledKerning" },
    { "sceFontGetScalePixel" },
    { "sceFontSetResolutionDpi" },
    { "sceFontSetScalePixel" },
    { "sceFontSetScalePoint" },
};

static const StubExport exports_FontFt[] = {
    { "sceFontSelectLibraryFt" },
    { "sceFontSelectRendererFt" },
};

static const StubExport exports_Share[] = {
    { "sceShareInitialize" },
    { "sceShareTerminate" },
    { "sceShareCaptureScreenshot" },
    { "sceShareCaptureVideoClip" },
    { "sceShareGetCurrentStatus" },
    { "sceShareSetScreenshotOverlayImage" },
    { "sceShareFeaturePermit" },
    { "sceShareFeatureProhibit" },
};

static const StubExport exports_Trophy2[] = {
    { "sceNpTrophy2CreateHandle" },
    { "sceNpTrophy2DestroyHandle" },
    { "sceNpTrophy2AbortHandle" },
    { "sceNpTrophy2CreateContext" },
    { "sceNpTrophy2DestroyContext" },
    { "sceNpTrophy2RegisterContext" },
    { "sceNpTrophy2RegisterUnlockCallback" },
    { "sceNpTrophy2UnregisterUnlockCallback" },
    { "sceNpTrophy2GetGameInfo" },
    { "sceNpTrophy2GetGroupInfo" },
    { "sceNpTrophy2GetGroupInfoArray" },
    { "sceNpTrophy2GetTrophyInfo" },
    { "sceNpTrophy2GetTrophyInfoArray" },
    { "sceNpTrophy2GetGameIcon" },
    { "sceNpTrophy2GetGroupIcon" },
    { "sceNpTrophy2GetTrophyIcon" },
    { "sceNpTrophy2GetRewardIcon" },
    { "sceNpTrophy2ShowTrophyList" },
};

static const StubExport exports_UniversalDataSystem[] = {
    { "sceNpUniversalDataSystemInitialize" },
    { "sceNpUniversalDataSystemTerminate" },
    { "sceNpUniversalDataSystemGetMemoryStat" },
    { "sceNpUniversalDataSystemCreateContext" },
    { "sceNpUniversalDataSystemDestroyContext" },
    { "sceNpUniversalDataSystemRegisterContext" },
    { "sceNpUniversalDataSystemCreateHandle" },
    { "sceNpUniversalDataSystemDestroyHandle" },
    { "sceNpUniversalDataSystemAbortHandle" },
    { "sceNpUniversalDataSystemPostEvent" },
    { "sceNpUniversalDataSystemCreateEvent" },
    { "sceNpUniversalDataSystemDestroyEvent" },
    { "sceNpUniversalDataSystemEventEstimateSize" },
    { "sceNpUniversalDataSystemEventToString" },
    { "sceNpUniversalDataSystemCreateEventPropertyObject" },
    { "sceNpUniversalDataSystemDestroyEventPropertyObject" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetString" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetInt32" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetUInt32" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetInt64" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetUInt64" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetFloat32" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetFloat64" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetBool" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetBinary" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetObject" },
    { "sceNpUniversalDataSystemEventPropertyObjectSetArray" },
    { "sceNpUniversalDataSystemCreateEventPropertyArray" },
    { "sceNpUniversalDataSystemDestroyEventPropertyArray" },
    { "sceNpUniversalDataSystemEventPropertyArraySetString" },
    { "sceNpUniversalDataSystemEventPropertyArraySetInt32" },
    { "sceNpUniversalDataSystemEventPropertyArraySetUInt32" },
    { "sceNpUniversalDataSystemEventPropertyArraySetInt64" },
    { "sceNpUniversalDataSystemEventPropertyArraySetUInt64" },
    { "sceNpUniversalDataSystemEventPropertyArraySetFloat32" },
    { "sceNpUniversalDataSystemEventPropertyArraySetFloat64" },
    { "sceNpUniversalDataSystemEventPropertyArraySetBool" },
    { "sceNpUniversalDataSystemEventPropertyArraySetBinary" },
    { "sceNpUniversalDataSystemEventPropertyArraySetObject" },
    { "sceNpUniversalDataSystemEventPropertyArraySetArray" },
    { "sceNpUniversalDataSystemGetStorageStat" },
};

static const StubExport exports_Notification[] = {
    { "sceNotificationSend" },
    { "sceNotificationSendById" },
    { "sceNotificationShowPsButtonPersistentBanner" },
    { "sceNotificationHidePsButtonPersistentBanner" },
};

static const StubExport exports_BluetoothHid[] = {
    { "sceBluetoothHidInit" },
    { "sceBluetoothHidParamInitialize" },
    { "sceBluetoothHidThreadParamInitialize" },
    { "sceBluetoothHidRegisterCallback" },
    { "sceBluetoothHidUnregisterCallback" },
    { "sceBluetoothHidRegisterDevice" },
    { "sceBluetoothHidUnregisterDevice" },
    { "sceBluetoothHidGetReportDescriptor" },
    { "sceBluetoothHidGetDeviceName" },
    { "sceBluetoothHidGetDeviceInfo" },
    { "sceBluetoothHidGetInputReport" },
    { "sceBluetoothHidGetFeatureReport" },
    { "sceBluetoothHidSetOutputReport" },
    { "sceBluetoothHidSetFeatureReport" },
    { "sceBluetoothHidInterruptOutput" },
    { "sceBluetoothHidDisconnectDevice" },
    { "sceBluetoothHidDebugGetVersion" },
};

static const StubExport exports_CffMgr[] = {
    { "sceConsoleFeatureFlagManagerIsOn" },
    { "sceConsoleFeatureFlagManagerIsWaitingReboot" },
};

static const StubExport exports_Camera2[] = {
    { "sceCamera2Close" },
    { "sceCamera2Finalize" },
    { "sceCamera2GetAttribute" },
    { "sceCamera2GetAutoExposureGain" },
    { "sceCamera2GetAutoWhiteBalance" },
    { "sceCamera2GetConfig" },
    { "sceCamera2GetExposureGain" },
    { "sceCamera2GetFieldOfView" },
    { "sceCamera2GetFrameData" },
    { "sceCamera2GetWhiteBalance" },
    { "sceCamera2Initialize" },
    { "sceCamera2IsAttached" },
    { "sceCamera2IsValidFrameData" },
    { "sceCamera2Open" },
    { "sceCamera2SetAttribute" },
    { "sceCamera2SetAutoExposureGain" },
    { "sceCamera2SetAutoWhiteBalance" },
    { "sceCamera2SetConfig" },
    { "sceCamera2SetExposureGain" },
    { "sceCamera2SetVideoSync" },
    { "sceCamera2SetWhiteBalance" },
    { "sceCamera2Start" },
    { "sceCamera2Stop" },
};

static const StubExport exports_Coredump[] = {
    { "sceCoredumpAttachMemoryRegion" },
    { "sceCoredumpAttachMemoryRegionAsUserFile" },
    { "sceCoredumpAttachUserFile" },
    { "sceCoredumpAttachUserMemoryFile" },
    { "sceCoredumpConfigDumpMode" },
    { "sceCoredumpDebugTextOut" },
    { "sceCoredumpGetStopInfoCpu" },
    { "sceCoredumpGetStopInfoGpu" },
    { "sceCoredumpGetThreadContextInfo" },
    { "sceCoredumpRegisterCoredumpHandler" },
    { "sceCoredumpUnregisterCoredumpHandler" },
    { "sceCoredumpWriteUserData" },
};

static const StubExport exports_Agc[] = {
    { "sceAgcAcbAcquireMem" },
    { "sceAgcAcbAcquireMemGetSize" },
    { "sceAgcAcbAtomicGds" },
    { "sceAgcAcbAtomicGdsGetSize" },
    { "sceAgcAcbAtomicMem" },
    { "sceAgcAcbAtomicMemGetSize" },
    { "sceAgcAcbCondExec" },
    { "sceAgcAcbCondExecGetSize" },
    { "sceAgcAcbCopyData" },
    { "sceAgcAcbCopyDataGetSize" },
    { "sceAgcAcbDispatchIndirect" },
    { "sceAgcAcbDispatchIndirectGetSize" },
    { "sceAgcAcbDmaData" },
    { "sceAgcAcbDmaDataGetSize" },
    { "sceAgcAcbEventWrite" },
    { "sceAgcAcbEventWriteGetSize" },
    { "sceAgcAcbJump" },
    { "sceAgcAcbJumpGetSize" },
    { "sceAgcAcbMemSemaphore" },
    { "sceAgcAcbPopMarker" },
    { "sceAgcAcbPrimeUtcl2" },
    { "sceAgcAcbPrimeUtcl2GetSize" },
    { "sceAgcAcbPushMarker" },
    { "sceAgcAcbQueueEndOfShaderActionGetSize" },
    { "sceAgcAcbResetQueue" },
    { "sceAgcAcbRewind" },
    { "sceAgcAcbRewindGetSize" },
    { "sceAgcAcbSetFlip" },
    { "sceAgcAcbSetMarker" },
    { "sceAgcAcbWaitOnAddressGetSize" },
    { "sceAgcAcbWaitRegMem" },
    { "sceAgcAcbWaitUntilSafeForRendering" },
    { "sceAgcAcbWriteData" },
    { "sceAgcAsyncCondExecPatchSetCommandAddress" },
    { "sceAgcAsyncCondExecPatchSetEnd" },
    { "sceAgcAsyncRewindPatchSetRewindState" },
    { "sceAgcBranchPatchSetCompareAddress" },
    { "sceAgcBranchPatchSetElseTarget" },
    { "sceAgcBranchPatchSetThenTarget" },
    { "sceAgcCbBranch" },
    { "sceAgcCbBranchGetSize" },
    { "sceAgcCbCondWrite" },
    { "sceAgcCbCondWriteGetSize" },
    { "sceAgcCbDispatch" },
    { "sceAgcCbDispatchGetSize" },
    { "sceAgcCbMemSemaphore" },
    { "sceAgcCbNop" },
    { "sceAgcCbNopGetSize" },
    { "sceAgcCbQueueEndOfPipeActionGetSize" },
    { "sceAgcCbReleaseMem" },
    { "sceAgcCbSetShRegisterRangeDirect" },
    { "sceAgcCbSetShRegisterRangeDirectGetSize" },
    { "sceAgcCbSetShRegistersDirect" },
    { "sceAgcCbSetShRegistersDirectGetSize" },
    { "sceAgcCbSetUcRegisterRangeDirect" },
    { "sceAgcCbSetUcRegisterRangeDirectGetSize" },
    { "sceAgcCbSetUcRegistersDirect" },
    { "sceAgcCbSetUcRegistersDirectGetSize" },
    { "sceAgcCondExecPatchSetCommandAddress" },
    { "sceAgcCondExecPatchSetEnd" },
    { "sceAgcCreateInterpolantMapping" },
    { "sceAgcCreatePrimState" },
    { "sceAgcCreateShader" },
    { "sceAgcDcbAcquireMem" },
    { "sceAgcDcbAcquireMemGetSize" },
    { "sceAgcDcbAtomicGds" },
    { "sceAgcDcbAtomicGdsGetSize" },
    { "sceAgcDcbAtomicMem" },
    { "sceAgcDcbAtomicMemGetSize" },
    { "sceAgcDcbBeginOcclusionQueryGetSize" },
    { "sceAgcDcbClearState" },
    { "sceAgcDcbCondExec" },
    { "sceAgcDcbCondExecGetSize" },
    { "sceAgcDcbContextStateOp" },
    { "sceAgcDcbContextStateOpGetSize" },
    { "sceAgcDcbCopyData" },
    { "sceAgcDcbCopyDataGetSize" },
    { "sceAgcDcbDispatchIndirect" },
    { "sceAgcDcbDispatchIndirectGetSize" },
    { "sceAgcDcbDmaData" },
    { "sceAgcDcbDmaDataGetSize" },
    { "sceAgcDcbDrawIndex" },
    { "sceAgcDcbDrawIndexAuto" },
    { "sceAgcDcbDrawIndexAutoGetSize" },
    { "sceAgcDcbDrawIndexGetSize" },
    { "sceAgcDcbDrawIndexIndirect" },
    { "sceAgcDcbDrawIndexIndirectGetSize" },
    { "sceAgcDcbDrawIndexIndirectMulti" },
    { "sceAgcDcbDrawIndexIndirectMultiGetSize" },
    { "sceAgcDcbDrawIndexMultiInstanced" },
    { "sceAgcDcbDrawIndexMultiInstancedGetSize" },
    { "sceAgcDcbDrawIndexOffset" },
    { "sceAgcDcbDrawIndexOffsetGetSize" },
    { "sceAgcDcbDrawIndirect" },
    { "sceAgcDcbDrawIndirectGetSize" },
    { "sceAgcDcbDrawIndirectMulti" },
    { "sceAgcDcbDrawIndirectMultiGetSize" },
    { "sceAgcDcbEndOcclusionQueryGetSize" },
    { "sceAgcDcbEventWrite" },
    { "sceAgcDcbEventWriteGetSize" },
    { "sceAgcDcbGetLodStats" },
    { "sceAgcDcbGetLodStatsGetSize" },
    { "sceAgcDcbJump" },
    { "sceAgcDcbJumpGetSize" },
    { "sceAgcDcbMemSemaphore" },
    { "sceAgcDcbPopMarker" },
    { "sceAgcDcbPrimeUtcl2" },
    { "sceAgcDcbPrimeUtcl2GetSize" },
    { "sceAgcDcbPushMarker" },
    { "sceAgcDcbQueueEndOfShaderActionGetSize" },
    { "sceAgcDcbResetQueue" },
    { "sceAgcDcbRewind" },
    { "sceAgcDcbRewindGetSize" },
    { "sceAgcDcbSetBaseDispatchIndirectArgsGetSize" },
    { "sceAgcDcbSetBaseDrawIndirectArgsGetSize" },
    { "sceAgcDcbSetBaseIndirectArgs" },
    { "sceAgcDcbSetBoolPredicationEnableGetSize" },
    { "sceAgcDcbSetCfRegisterDirect" },
    { "sceAgcDcbSetCfRegisterRangeDirect" },
    { "sceAgcDcbSetCxRegisterDirect" },
    { "sceAgcDcbSetCxRegisterDirectGetSize" },
    { "sceAgcDcbSetCxRegistersIndirect" },
    { "sceAgcDcbSetCxRegistersIndirectGetSize" },
    { "sceAgcDcbSetFlip" },
    { "sceAgcDcbSetIndexBuffer" },
    { "sceAgcDcbSetIndexBufferGetSize" },
    { "sceAgcDcbSetIndexCount" },
    { "sceAgcDcbSetIndexCountGetSize" },
    { "sceAgcDcbSetIndexIndirectArgs" },
    { "sceAgcDcbSetIndexIndirectArgsGetSize" },
    { "sceAgcDcbSetIndexSize" },
    { "sceAgcDcbSetIndexSizeGetSize" },
    { "sceAgcDcbSetMarker" },
    { "sceAgcDcbSetNumInstances" },
    { "sceAgcDcbSetNumInstancesGetSize" },
    { "sceAgcDcbSetPredication" },
    { "sceAgcDcbSetPredicationDisableGetSize" },
    { "sceAgcDcbSetShRegisterDirect" },
    { "sceAgcDcbSetShRegisterDirectGetSize" },
    { "sceAgcDcbSetShRegistersIndirect" },
    { "sceAgcDcbSetShRegistersIndirectGetSize" },
    { "sceAgcDcbSetUcRegisterDirect" },
    { "sceAgcDcbSetUcRegisterDirectGetSize" },
    { "sceAgcDcbSetUcRegistersIndirect" },
    { "sceAgcDcbSetUcRegistersIndirectGetSize" },
    { "sceAgcDcbSetZPassPredicationEnableGetSize" },
    { "sceAgcDcbStallCommandBufferParser" },
    { "sceAgcDcbStallCommandBufferParserGetSize" },
    { "sceAgcDcbWaitOnAddressGetSize" },
    { "sceAgcDcbWaitRegMem" },
    { "sceAgcDcbWaitUntilSafeForRendering" },
    { "sceAgcDcbWriteData" },
    { "sceAgcDcbWriteDataGetSize" },
    { "sceAgcDmaDataPatchSetDstAddressOrOffset" },
    { "sceAgcDmaDataPatchSetSrcAddressOrOffsetOrImmediate" },
    { "sceAgcFuseShaderHalves" },
    { "sceAgcGetDataPacketPayloadAddress" },
    { "sceAgcGetFusedShaderSize" },
    { "sceAgcGetPacketSize" },
    { "sceAgcGetRegisterDefaults" },
    { "sceAgcGetRegisterDefaults2" },
    { "sceAgcGetRegisterDefaults2Internal" },
    { "sceAgcGetRegisterDefaultsInternal" },
    { "sceAgcInit" },
    { "sceAgcJumpPatchSetTarget" },
    { "sceAgcLinkShaders" },
    { "sceAgcQueueEndOfPipeActionPatchAddress" },
    { "sceAgcQueueEndOfPipeActionPatchData" },
    { "sceAgcQueueEndOfPipeActionPatchGcrCntl" },
    { "sceAgcQueueEndOfPipeActionPatchType" },
    { "sceAgcRewindPatchSetRewindState" },
    { "sceAgcSetCxRegIndirectPatchAddRegisters" },
    { "sceAgcSetCxRegIndirectPatchSetAddress" },
    { "sceAgcSetCxRegIndirectPatchSetNumRegisters" },
    { "sceAgcSetNop" },
    { "sceAgcSetPacketPredication" },
    { "sceAgcSetRangePredication" },
    { "sceAgcSetShRegIndirectPatchAddRegisters" },
    { "sceAgcSetShRegIndirectPatchSetAddress" },
    { "sceAgcSetShRegIndirectPatchSetNumRegisters" },
    { "sceAgcSetSubmitMode" },
    { "sceAgcSetUcRegIndirectPatchAddRegisters" },
    { "sceAgcSetUcRegIndirectPatchSetAddress" },
    { "sceAgcSetUcRegIndirectPatchSetNumRegisters" },
    { "sceAgcSuspendPoint" },
    { "sceAgcSuspendPointAndCheckStatus" },
    { "sceAgcUpdateInterpolantMapping" },
    { "sceAgcUpdatePrimState" },
    { "sceAgcWaitRegMemPatchAddress" },
    { "sceAgcWaitRegMemPatchCompareFunction" },
    { "sceAgcWaitRegMemPatchMask" },
    { "sceAgcWaitRegMemPatchReference" },
};

static const StubExport exports_AgcDriver[] = {
    { "sceAgcDriverAddEqEvent" },
    { "sceAgcDriverAgrSubmitDcb" },
    { "sceAgcDriverAgrSubmitMultiDcbs" },
    { "sceAgcDriverCreateQueue" },
    { "sceAgcDriverCwsrResumeAcq" },
    { "sceAgcDriverCwsrSuspendAcq" },
    { "sceAgcDriverDebugHardwareStatus" },
    { "sceAgcDriverDeleteEqEvent" },
    { "sceAgcDriverDestroyQueue" },
    { "sceAgcDriverFindResourcesPublic" },
    { "sceAgcDriverGetEqContextId" },
    { "sceAgcDriverGetEqEventType" },
    { "sceAgcDriverGetGpuRefClks" },
    { "sceAgcDriverGetHsOffchipParam" },
    { "sceAgcDriverGetOwnerName" },
    { "sceAgcDriverGetRegShadowInfo" },
    { "sceAgcDriverGetRegShadowInfoAgr" },
    { "sceAgcDriverGetReservedDmemForAgc" },
    { "sceAgcDriverGetResourceBaseAddressAndSizeInBytes" },
    { "sceAgcDriverGetResourceName" },
    { "sceAgcDriverGetResourceShaderGuid" },
    { "sceAgcDriverGetResourceType" },
    { "sceAgcDriverGetResourceUserData" },
    { "sceAgcDriverGetSetFlipPacketSizeInDwords" },
    { "sceAgcDriverGetSetWorkloadCompletePacketSize" },
    { "sceAgcDriverGetSetWorkloadsActivePacketSize" },
    { "sceAgcDriverGetTFRing" },
    { "sceAgcDriverGetTraceInitiator" },
    { "sceAgcDriverGetWaitRenderingPacketSizeInDwords" },
    { "sceAgcDriverGetWorkloadStreamInfo" },
    { "sceAgcDriverIDHSSubmit" },
    { "sceAgcDriverInitResourceRegistration" },
    { "sceAgcDriverIsCaptureInProgress" },
    { "sceAgcDriverIsSubmitValidationEnabled" },
    { "sceAgcDriverIsTraceInProgress" },
    { "sceAgcDriverModuleRegistration" },
    { "sceAgcDriverNotifyDefaultStates" },
    { "sceAgcDriverPassInfoDownward" },
    { "sceAgcDriverPatchClearState" },
    { "sceAgcDriverQueryResourceRegistrationUserMemoryRequirements" },
    { "sceAgcDriverRegisterGdsResource" },
    { "sceAgcDriverRegisterOwner" },
    { "sceAgcDriverRegisterResource" },
    { "sceAgcDriverRegisterWorkloadStream" },
    { "sceAgcDriverRequestCaptureStart" },
    { "sceAgcDriverRequestCaptureStop" },
    { "sceAgcDriverSetFlip" },
    { "sceAgcDriverSetHsOffchipParam" },
    { "sceAgcDriverSetResourceUserData" },
    { "sceAgcDriverSetTFRing" },
    { "sceAgcDriverSetWorkloadComplete" },
    { "sceAgcDriverSetWorkloadsActive" },
    { "sceAgcDriverSetupRegisterShadow" },
    { "sceAgcDriverSubmitAcb" },
    { "sceAgcDriverSubmitCommandBuffer" },
    { "sceAgcDriverSubmitDcb" },
    { "sceAgcDriverSubmitMultiAcbs" },
    { "sceAgcDriverSubmitMultiCommandBuffers" },
    { "sceAgcDriverSubmitMultiDcbs" },
    { "sceAgcDriverSuspendPointSubmit" },
    { "sceAgcDriverSysEnableSubmitDone45Exception" },
    { "sceAgcDriverSysGetClientNumber" },
    { "sceAgcDriverSysIsGameClosed" },
    { "sceAgcDriverSysSubmitFlipHandleProxy" },
    { "sceAgcDriverTmpInitIdhs" },
    { "sceAgcDriverTriggerCapture" },
    { "sceAgcDriverUnregisterAllResourcesForOwner" },
    { "sceAgcDriverUnregisterOwnerAndResources" },
    { "sceAgcDriverUnregisterResource" },
    { "sceAgcDriverUnregisterWorkloadStream" },
    { "sceAgcDriverUserDataGetPacketSize" },
    { "sceAgcDriverUserDataImmediateWrite" },
    { "sceAgcDriverUserDataWritePacket" },
    { "sceAgcDriverUserDataWritePopMarker" },
    { "sceAgcDriverUserDataWritePushMarker" },
    { "sceAgcDriverUserDataWriteSetMarker" },
    { "sceAgcDriverWaitUntilSafeForRendering" },
};

const StubEntry ps5link_catalog[] = {
    { "libkernel", "libkernel", "libkernel.prx", 0x0101, 0x0001, exports_Kernel, sizeof(exports_Kernel) / sizeof(exports_Kernel[0]) },
    { "libScePosix", "libkernel", "libkernel.prx", 0x0101, 0x0001, exports_Posix, sizeof(exports_Posix) / sizeof(exports_Posix[0]) },
    { "libSceOpenPsId", "libkernel", "libkernel.prx", 0x0101, 0x0001, exports_OpenPsId, sizeof(exports_OpenPsId) / sizeof(exports_OpenPsId[0]) },
    { "libc", "libc", "libc.prx", 0x0101, 0x0001, exports_C, sizeof(exports_C) / sizeof(exports_C[0]) },
    { "libSceVideoOut", "libSceVideoOut", "libSceVideoOut.prx", 0x0101, 0x0001, exports_VideoOut, sizeof(exports_VideoOut) / sizeof(exports_VideoOut[0]) },
    { "libScePad", "libScePad", "libScePad.prx", 0x0101, 0x0001, exports_Pad, sizeof(exports_Pad) / sizeof(exports_Pad[0]) },
    { "libSceUserService", "libSceUserService", "libSceUserService.prx", 0x0101, 0x0001, exports_UserService, sizeof(exports_UserService) / sizeof(exports_UserService[0]) },
    { "libSceSystemService", "libSceSystemService", "libSceSystemService.prx", 0x0101, 0x0001, exports_SystemService, sizeof(exports_SystemService) / sizeof(exports_SystemService[0]) },
    { "libSceAudioOut", "libSceAudioOut", "libSceAudioOut.prx", 0x0101, 0x0001, exports_AudioOut, sizeof(exports_AudioOut) / sizeof(exports_AudioOut[0]) },
    { "libSceAudioOut2", "libSceAudioOut", "libSceAudioOut.prx", 0x0101, 0x0001, exports_AudioOut2, sizeof(exports_AudioOut2) / sizeof(exports_AudioOut2[0]) },
    { "libSceSysmodule", "libSceSysmodule", "libSceSysmodule.prx", 0x0101, 0x0001, exports_Sysmodule, sizeof(exports_Sysmodule) / sizeof(exports_Sysmodule[0]) },
    { "libScePngDec", "libScePngDec", "libScePngDec.prx", 0x0101, 0x0001, exports_PngDec, sizeof(exports_PngDec) / sizeof(exports_PngDec[0]) },
    { "libScePngEnc", "libScePngEnc", "libScePngEnc.prx", 0x0101, 0x0001, exports_PngEnc, sizeof(exports_PngEnc) / sizeof(exports_PngEnc[0]) },
    { "libSceJpegDec", "libSceJpegDec", "libSceJpegDec.prx", 0x0101, 0x0001, exports_JpegDec, sizeof(exports_JpegDec) / sizeof(exports_JpegDec[0]) },
    { "libSceJpegEnc", "libSceJpegEnc", "libSceJpegEnc.prx", 0x0101, 0x0001, exports_JpegEnc, sizeof(exports_JpegEnc) / sizeof(exports_JpegEnc[0]) },
    { "libSceAudioIn", "libSceAudioIn", "libSceAudioIn.prx", 0x0101, 0x0001, exports_AudioIn, sizeof(exports_AudioIn) / sizeof(exports_AudioIn[0]) },
    { "libSceAudiodec", "libSceAudiodec", "libSceAudiodec.native.prx", 0x0101, 0x0001, exports_Audiodec, sizeof(exports_Audiodec) / sizeof(exports_Audiodec[0]) },
    { "libSceM4aacEnc", "libSceM4aacEnc", "libSceM4aacEnc.prx", 0x0101, 0x0001, exports_M4aacEnc, sizeof(exports_M4aacEnc) / sizeof(exports_M4aacEnc[0]) },
    { "libSceAt9Enc", "libSceAt9Enc", "libSceAt9Enc.prx", 0x0101, 0x0001, exports_At9Enc, sizeof(exports_At9Enc) / sizeof(exports_At9Enc[0]) },
    { "libSceNgs2", "libSceNgs2", "libSceNgs2.prx", 0x0101, 0x0001, exports_Ngs2, sizeof(exports_Ngs2) / sizeof(exports_Ngs2[0]) },
    { "libSceAudio3d", "libSceAudio3d", "libSceAudio3d.prx", 0x0101, 0x0001, exports_Audio3d, sizeof(exports_Audio3d) / sizeof(exports_Audio3d[0]) },
    { "libSceAjm", "libSceAjm", "libSceAjm.native.prx", 0x0101, 0x0001, exports_Ajm, sizeof(exports_Ajm) / sizeof(exports_Ajm[0]) },
    { "libSceVideoRecordingP", "libSceVideoRecording", "libSceVideoRecording.native.prx", 0x0101, 0x0001, exports_VideoRecording, sizeof(exports_VideoRecording) / sizeof(exports_VideoRecording[0]) },
    { "libSceCes", "libSceCes", "libSceCesCs-module.prx", 0x0101, 0x0001, exports_Ces, sizeof(exports_Ces) / sizeof(exports_Ces[0]) },
    { "libSceDepth2", "libSceDepth2", "libSceDepth2.prx", 0x0101, 0x0001, exports_Depth2, sizeof(exports_Depth2) / sizeof(exports_Depth2[0]) },
    { "libSceDeviceService", "libSceMbus", "libSceMbus.prx", 0x0101, 0x0001, exports_DeviceService, sizeof(exports_DeviceService) / sizeof(exports_DeviceService[0]) },
    { "libSceVideodec2", "libSceVideodec2", "libSceVideodec2.prx", 0x0101, 0x0001, exports_Videodec2, sizeof(exports_Videodec2) / sizeof(exports_Videodec2[0]) },
    { "libSceRtc", "libSceRtc", "libSceRtc.prx", 0x0101, 0x0001, exports_Rtc, sizeof(exports_Rtc) / sizeof(exports_Rtc[0]) },
    { "libSceRandom", "libSceRandom", "libSceRandom.prx", 0x0101, 0x0001, exports_Random, sizeof(exports_Random) / sizeof(exports_Random[0]) },
    { "libSceZlib", "libSceZlib", "libSceZlib.prx", 0x0101, 0x0001, exports_Zlib, sizeof(exports_Zlib) / sizeof(exports_Zlib[0]) },
    { "libSceNet", "libSceNet", "libSceNet.prx", 0x0101, 0x0001, exports_Net, sizeof(exports_Net) / sizeof(exports_Net[0]) },
    { "libSceSsl", "libSceSsl", "libSceSsl.prx", 0x0201, 0x0001, exports_Ssl, sizeof(exports_Ssl) / sizeof(exports_Ssl[0]) },
    { "libSceHttp", "libSceHttp", "libSceHttp.prx", 0x0101, 0x0001, exports_Http, sizeof(exports_Http) / sizeof(exports_Http[0]) },
    { "libSceHttp2", "libSceHttp2", "libSceHttp2.prx", 0x0101, 0x0001, exports_Http2, sizeof(exports_Http2) / sizeof(exports_Http2[0]) },
    { "libkernel_sys", "libkernel", "libkernel.prx", 0x0101, 0x0001, exports_KernelSys, sizeof(exports_KernelSys) / sizeof(exports_KernelSys[0]) },
    { "libSceContentDelete", "libSceContentDelete", "libSceContentDelete.prx", 0x0101, 0x0001, exports_ContentDelete, sizeof(exports_ContentDelete) / sizeof(exports_ContentDelete[0]) },
    { "libSceContentExport", "libSceContentExport", "libSceContentExport.prx", 0x0101, 0x0001, exports_ContentExport, sizeof(exports_ContentExport) / sizeof(exports_ContentExport[0]) },
    { "libSceContentSearch", "libSceContentSearch", "libSceContentSearch.prx", 0x0100, 0x0001, exports_ContentSearch, sizeof(exports_ContentSearch) / sizeof(exports_ContentSearch[0]) },
    { "libScePlayGo", "libScePlayGo", "libScePlayGo.prx", 0x0100, 0x0001, exports_PlayGo, sizeof(exports_PlayGo) / sizeof(exports_PlayGo[0]) },
    { "libSceAppContent", "libSceAppContentUtil", "libSceAppContent.prx", 0x0101, 0x0001, exports_AppContent, sizeof(exports_AppContent) / sizeof(exports_AppContent[0]) },
    { "libSceNetCtl", "libSceNetCtl", "libSceNetCtl.prx", 0x0101, 0x0001, exports_NetCtl, sizeof(exports_NetCtl) / sizeof(exports_NetCtl[0]) },
    { "libSceSaveData_native", "libSceSaveData_native", "libSceSaveData.native.prx", 0x0101, 0x0001, exports_SaveData, sizeof(exports_SaveData) / sizeof(exports_SaveData[0]) },
    { "libSceKeyboard", "libSceKeyboard", "libSceKeyboard.prx", 0x0101, 0x0001, exports_Keyboard, sizeof(exports_Keyboard) / sizeof(exports_Keyboard[0]) },
    { "libSceMouse", "libSceMouse", "libSceMouse.prx", 0x0101, 0x0001, exports_Mouse, sizeof(exports_Mouse) / sizeof(exports_Mouse[0]) },
    { "libSceCommonDialog", "libSceCommonDialog", "libSceCommonDialog.prx", 0x0101, 0x0001, exports_CommonDialog, sizeof(exports_CommonDialog) / sizeof(exports_CommonDialog[0]) },
    { "libSceImeDialog", "libSceImeDialog", "libSceImeDialog.prx", 0x0101, 0x0001, exports_ImeDialog, sizeof(exports_ImeDialog) / sizeof(exports_ImeDialog[0]) },
    { "libSceErrorDialog", "libSceErrorDialog", "libSceErrorDialog.prx", 0x0101, 0x0001, exports_ErrorDialog, sizeof(exports_ErrorDialog) / sizeof(exports_ErrorDialog[0]) },
    { "libSceMsgDialog.native", "libSceMsgDialog", "libSceMsgDialog.native.prx", 0x0101, 0x0001, exports_MsgDialog, sizeof(exports_MsgDialog) / sizeof(exports_MsgDialog[0]) },
    { "libSceSaveDataDialog.native", "libSceSaveDataDialog", "libSceSaveDataDialog.native.prx", 0x0101, 0x0001, exports_SaveDataDialog, sizeof(exports_SaveDataDialog) / sizeof(exports_SaveDataDialog[0]) },
    { "libSceWebBrowserDialog", "libSceWebBrowserDialog", "libSceWebBrowserDialog.prx", 0x0101, 0x0001, exports_WebBrowserDialog, sizeof(exports_WebBrowserDialog) / sizeof(exports_WebBrowserDialog[0]) },
    { "libSceAvPlayer", "libSceAvPlayer", "libSceAvPlayer.native.prx", 0x0100, 0x0001, exports_AvPlayer, sizeof(exports_AvPlayer) / sizeof(exports_AvPlayer[0]) },
    { "libSceFont", "libSceFont", "libSceFont-module.prx", 0x0101, 0x0001, exports_Font, sizeof(exports_Font) / sizeof(exports_Font[0]) },
    { "libSceFontFt", "libSceFontFt", "libSceFontFt-module.prx", 0x0101, 0x0001, exports_FontFt, sizeof(exports_FontFt) / sizeof(exports_FontFt[0]) },
    { "libSceShare", "libSceShare", "libSceShare.prx", 0x0101, 0x0001, exports_Share, sizeof(exports_Share) / sizeof(exports_Share[0]) },
    { "libSceNpTrophy2", "libSceNpTrophy2", "libSceNpTrophy2.prx", 0x0101, 0x0001, exports_Trophy2, sizeof(exports_Trophy2) / sizeof(exports_Trophy2[0]) },
    { "libSceNpUniversalDataSystem", "libSceNpUniversalDataSystem", "libSceNpUniversalDataSystem.prx", 0x0101, 0x0001, exports_UniversalDataSystem, sizeof(exports_UniversalDataSystem) / sizeof(exports_UniversalDataSystem[0]) },
    { "libSceNotification", "libSceNotification", "libSceNotification.prx", 0x0101, 0x0001, exports_Notification, sizeof(exports_Notification) / sizeof(exports_Notification[0]) },
    { "libSceBluetoothHid", "libSceBluetoothHid", "libSceBluetoothHid.prx", 0x0101, 0x0001, exports_BluetoothHid, sizeof(exports_BluetoothHid) / sizeof(exports_BluetoothHid[0]) },
    { "libSceCffMgr", "libSceCffMgr", "libSceCffMgr.prx", 0x0101, 0x0001, exports_CffMgr, sizeof(exports_CffMgr) / sizeof(exports_CffMgr[0]) },
    { "libSceCamera2", "libSceCamera", "libSceCamera.prx", 0x0101, 0x0001, exports_Camera2, sizeof(exports_Camera2) / sizeof(exports_Camera2[0]) },
    { "libSceCoredump", "libkernel", "libkernel.prx", 0x0101, 0x0001, exports_Coredump, sizeof(exports_Coredump) / sizeof(exports_Coredump[0]) },
    { "libSceAgc", "libSceAgc", "libSceAgc.prx", 0x0101, 0x0001, exports_Agc, sizeof(exports_Agc) / sizeof(exports_Agc[0]) },
    { "libSceAgcDriver", "libSceAgcDriver", "libSceAgcDriver.prx", 0x0101, 0x0001, exports_AgcDriver, sizeof(exports_AgcDriver) / sizeof(exports_AgcDriver[0]) },
};

const size_t ps5link_catalog_count = sizeof(ps5link_catalog) / sizeof(ps5link_catalog[0]);
