#ifndef PS5LINK_CATALOG_H
#define PS5LINK_CATALOG_H

/* Generated by gen_catalog.py from SharpProspero.Prx/StubCatalog.cs. Do not
 * hand-edit - re-run the generator instead. Hand-picked extra entries (for
 * names StubCatalog.cs doesn't cover yet) live in catalog_extra.c/.h, kept
 * separate so a re-run of the generator never clobbers them. catalog_find()
 * (in catalog_lookup.c, also hand-written) searches both tables. */

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *plain_name;
} StubExport;

typedef struct {
    const char *library;        /* library name an import resolves against */
    const char *module_name;    /* module name the providing module publishes (never NULL after generation) */
    const char *soname;         /* module file name the loader loads (never NULL after generation) */
    uint16_t module_version;
    uint16_t library_version;
    const StubExport *exports;
    size_t export_count;
} StubEntry;

extern const StubEntry ps5link_catalog[];
extern const size_t ps5link_catalog_count;

#endif
