#!/usr/bin/env python3
"""
One-time, throwaway generator: parses SharpProspero.Prx/StubCatalog.cs's
`Core` table (hand-curated plain-name -> module/library catalog, validated
against real on-device modules) and emits catalog.c/catalog.h for ps5link.

Not part of PS5SDK's build - run by hand once (and again only if
StubCatalog.cs gains new entries worth picking up). No dotnet dependency
introduced into the C toolchain.
"""
import re
import sys

# Path to SharpProspero's tools/SharpProspero.Prx/StubCatalog.cs.
SRC = sys.argv[1] if len(sys.argv) > 1 else "StubCatalog.cs"
OUT_C = "catalog.c"
OUT_H = "catalog.h"

DEFAULT_MODULE_VERSION = 0x0101
DEFAULT_LIBRARY_VERSION = 0x0001


def strip_line_comments(text):
    out_lines = []
    for line in text.split("\n"):
        idx = line.find("//")
        out_lines.append(line if idx < 0 else line[:idx])
    return "\n".join(out_lines)


def extract_block(text, start_marker):
    start = text.index(start_marker)
    open_idx = text.index("[", start)
    depth = 0
    i = open_idx
    while True:
        if text[i] == "[":
            depth += 1
        elif text[i] == "]":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return text[open_idx + 1:i]


def parse_entries(core_block):
    entries = []
    # new Entry("Library", ArrayName, ...optional named args..., ...)
    entry_re = re.compile(
        r'new Entry\(\s*"([^"]+)"\s*,\s*([A-Za-z0-9_]+)\s*(.*?)\)',
        re.DOTALL,
    )
    for m in entry_re.finditer(core_block):
        library, array_name, rest = m.group(1), m.group(2), m.group(3)
        module_version = DEFAULT_MODULE_VERSION
        library_version = DEFAULT_LIBRARY_VERSION
        module_name = None
        soname = None

        mv = re.search(r'ModuleVersion:\s*(0x[0-9A-Fa-f]+)', rest)
        if mv:
            module_version = int(mv.group(1), 16)
        lv = re.search(r'LibraryVersion:\s*(0x[0-9A-Fa-f]+|\d+)', rest)
        if lv:
            library_version = int(lv.group(1), 0)
        mn = re.search(r'ModuleName:\s*"([^"]+)"', rest)
        if mn:
            module_name = mn.group(1)
        sn = re.search(r'Soname:\s*"([^"]+)"', rest)
        if sn:
            soname = sn.group(1)

        entries.append({
            "library": library,
            "array_name": array_name,
            "module_version": module_version,
            "library_version": library_version,
            "module_name": module_name,
            "soname": soname,
        })
    return entries


def parse_arrays(text):
    """Finds every `private static readonly string[] Name = [ ... ];` array."""
    arrays = {}
    arr_re = re.compile(
        r'private static readonly string\[\]\s+([A-Za-z0-9_]+)\s*=\s*\[',
    )
    for m in arr_re.finditer(text):
        name = m.group(1)
        open_idx = m.end() - 1  # position of the '['
        depth = 0
        i = open_idx
        while True:
            if text[i] == "[":
                depth += 1
            elif text[i] == "]":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        body = text[open_idx + 1:i]
        names = re.findall(r'"([^"]+)"', body)
        arrays[name] = names
    return arrays


def c_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    with open(SRC, "r") as f:
        raw = f.read()
    text = strip_line_comments(raw)

    core_block = extract_block(text, "Core =>")
    entries = parse_entries(core_block)
    arrays = parse_arrays(text)

    missing = [e for e in entries if e["array_name"] not in arrays]
    if missing:
        print("ERROR: entries referencing arrays not found:", file=sys.stderr)
        for e in missing:
            print(f"  {e['library']} -> {e['array_name']}", file=sys.stderr)
        sys.exit(1)

    total_exports = sum(len(arrays[e["array_name"]]) for e in entries)
    print(f"Parsed {len(entries)} catalog entries, {total_exports} exported names total.")

    with open(OUT_H, "w") as f:
        f.write("""#ifndef PS5LINK_CATALOG_H
#define PS5LINK_CATALOG_H

/* Generated by gen_catalog.py from SharpProspero.Prx/StubCatalog.cs. Do not
 * hand-edit - re-run the generator instead. Hand-picked extra entries (for
 * names StubCatalog.cs doesn't cover yet) live in catalog_extra.c/.h, kept
 * separate so a re-run of the generator never clobbers them. catalog_find()
 * (in catalog_lookup.c, also hand-written) searches both tables. */

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *plain_name;
} StubExport;

typedef struct {
    const char *library;        /* library name an import resolves against */
    const char *module_name;    /* module name the providing module publishes (never NULL after generation) */
    const char *soname;         /* module file name the loader loads (never NULL after generation) */
    uint16_t module_version;
    uint16_t library_version;
    const StubExport *exports;
    size_t export_count;
} StubEntry;

extern const StubEntry ps5link_catalog[];
extern const size_t ps5link_catalog_count;

#endif
""")

    with open(OUT_C, "w") as f:
        f.write('#include "catalog.h"\n\n')
        for e in entries:
            names = arrays[e["array_name"]]
            f.write(f"static const StubExport exports_{e['array_name']}[] = {{\n")
            for n in names:
                f.write(f"    {{ {c_string(n)} }},\n")
            f.write("};\n\n")

        f.write("const StubEntry ps5link_catalog[] = {\n")
        for e in entries:
            module_name = e["module_name"] or e["library"]
            soname = e["soname"] or (e["library"] + ".prx")
            f.write(
                f"    {{ {c_string(e['library'])}, {c_string(module_name)}, {c_string(soname)}, "
                f"{e['module_version']:#06x}, {e['library_version']:#06x}, "
                f"exports_{e['array_name']}, "
                f"sizeof(exports_{e['array_name']}) / sizeof(exports_{e['array_name']}[0]) }},\n"
            )
        f.write("};\n\n")
        f.write("const size_t ps5link_catalog_count = sizeof(ps5link_catalog) / sizeof(ps5link_catalog[0]);\n")

    print(f"Wrote {OUT_H} and {OUT_C}")


if __name__ == "__main__":
    main()
